// app/layout.tsx
"use client";
import Providers from "./providers";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Appbar from "../../components/Appbar";
import { ChakraProvider, Container } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  preload: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CacheProvider>
          <ChakraProvider>
              <Appbar />
            
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from 'next'
// import { Poppins } from 'next/font/google'
// import { Providers } from './providers'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={poppins.className}>  <Providers>
//         {children}
//       </Providers></body>
//     </html>
//   )
// }
