// app/layout.tsx
"use client";
import Providers from "./providers";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Appbar from "../../components/Appbar";
import { Box, ChakraProvider, Container, Text } from "@chakra-ui/react";
import { CacheProvider } from "@chakra-ui/next-js";
import "./globals.css";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  preload: false,
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <CacheProvider>
          <ChakraProvider>
            <Box w="full" zIndex={"50"}  top="0" pos={"fixed"} mb="15">

            
            <Contact />
              <Appbar />
            </Box>
            
            {children}
          </ChakraProvider>
        </CacheProvider>
      </body>
    </html>
  );
}

const Contact = () => {
  return(<>
    <Box w="full" py="1" mb="0"  className="contact">
<Container maxW={"container.lg"}>

<Text textAlign={"right"} color={"white"}>Contact No : 7041303457</Text>
</Container>
    </Box>
  </>)
}

// import type { Metadata } from 'next'
// import { Poppins } from 'next/font/google'
// import { Providers } from './providers'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={poppins.className}>  <Providers>
//         {children}
//       </Providers></body>
//     </html>
//   )
// }
